version: "3.9"

services:
  caddy:
    build:
      context: ./caddy
      dockerfile: ./caddy/Dockerfile
      args:
        domain: "${${domain}:+keine.shop}",
        redir_host: ,
        auth_host: 
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    # profiles: ["reverse-proxy-caddy"]
    environment: 
      - LOG_PATH=/log
      - ROOT=/var/www/${${domain}:+keine.shop}
    volumes:
      - ${pwd}/assets/:/var/www/
      - /var/log/docker_apps/caddy:/log
      - caddy_data:/data       # named volume
      - caddy_config:/config   # named volume
    networks: 
      - frontend
  smtp:
    restart: on-failure
    build:
      context: ./mail-server
      dockerfile: ./mail-server/Dockerfile
      args:
        domain: "${${domain}:+keine.shop}"
        output_dir: /home/node/app/
    ports:
      - "587:587"
    volumes: 
      - ssl_data:/home/node/app/ssl/   # named volume, external
    networks: 
      - backend
  db:


secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt

volumes:
  caddy_data:
  caddy_config:
  ssl_data:
    external: true 

networks: 
  frontend:
  backend: